/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddNode: typeof import('./../src/components/flowChart/components/other/addNode/index.tsx')['default']
    Alias: typeof import('./../src/components/flowChart/lib/alias.tsx')['default']
    AllinSslThemeProvider: typeof import('./../src/components/AllinSslThemeProvider/index.tsx')['default']
    BaseLayout: typeof import('./../src/components/BaseLayout/index.tsx')['default']
    BaseNode: typeof import('./../src/components/flowChart/components/base/baseNode/index.tsx')['default']
    BranchNode: typeof import('./../src/components/flowChart/components/base/branchNode/index.tsx')['default']
    CAProviderSelect: typeof import('./../src/components/CAProviderSelect/index.tsx')['default']
    ConditionNode: typeof import('./../src/components/flowChart/components/base/conditionNode/index.tsx')['default']
    Config: typeof import('./../src/components/flowChart/lib/config.tsx')['default']
    Demo: typeof import('./../src/components/notifyProviderMultiSelect/demo.tsx')['default']
    DnsProviderSelect: typeof import('./../src/components/dnsProviderSelect/index.tsx')['default']
    Drawer: typeof import('./../src/components/flowChart/components/other/drawer.tsx')['default']
    EndNode: typeof import('./../src/components/flowChart/components/base/endNode.tsx')['default']
    ErrorNode: typeof import('./../src/components/flowChart/components/base/errorNode/index.tsx')['default']
    FlowChart: typeof import('./../src/components/flowChart/index.tsx')['default']
    InfoItem: typeof import('./../src/components/InfoItem/index.tsx')['default']
    LogDisplay: typeof import('./../src/components/LogDisplay/index.tsx')['default']
    NodeWrap: typeof import('./../src/components/flowChart/components/render/nodeWrap.tsx')['default']
    NotifyProviderMultiSelect: typeof import('./../src/components/notifyProviderMultiSelect/index.tsx')['default']
    NotifyProviderSelect: typeof import('./../src/components/notifyProviderSelect/index.tsx')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusCard: typeof import('./../src/components/StatusCard/index.tsx')['default']
    SvgIcon: typeof import('./../src/components/svgIcon/index.tsx')['default']
    TableEmptyState: typeof import('./../src/components/TableEmptyState/index.tsx')['default']
    ThemeProvider: typeof import('./../src/components/ThemeProvider/index.tsx')['default']
    ThemeToggle: typeof import('./../src/components/ThemeToggle/index.tsx')['default']
    TypeIcon: typeof import('./../src/components/typeIcon/index.tsx')['default']
    UpdateLogModal: typeof import('./../src/components/UpdateLogModal/index.tsx')['default']
    UseController: typeof import('./../src/components/CAProviderSelect/useController.tsx')['default']
    UseStore: typeof import('./../src/components/flowChart/useStore.tsx')['default']
    Verify: typeof import('./../src/components/flowChart/lib/verify.tsx')['default']
  }
}
